# Generated by Django 5.2.6 on 2025-09-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TypeCoverage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('tipo_cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='TypeCoverage.tipocobertura')),
            ],
        ),
    ]
