# Generated by Django 5.2.6 on 2025-09-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Commitment', '0001_initial'),
        ('ONG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos_responsables', to='ONG.ong'),
        ),
    ]
