# Generated by Django 5.2.6 on 2025-11-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commitment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
