# Generated by Django 5.2.6 on 2025-10-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
