# Generated by Django 5.2.6 on 2025-11-18 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverageRequest', '0001_initial'),
        ('Stage', '0004_alter_etapa_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='CoverageRequest.pedidocobertura'),
        ),
    ]
