# Generated by Django 5.2.6 on 2025-09-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BoardOfDirectors', '0001_initial'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('consejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='BoardOfDirectors.consejodirectivo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='Project.proyecto')),
            ],
        ),
    ]
