# Generated by Django 5.2.6 on 2025-11-17 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='observacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observacion',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
