# Generated by Django 5.2.6 on 2025-09-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ONG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('proceso', 'En proceso'), ('ejecucion', 'En ejecución'), ('finalizado', 'Finalizado')], default='proceso', max_length=20)),
                ('originador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_originados', to='ONG.ong')),
            ],
        ),
    ]
