# Generated by Django 5.2.6 on 2025-09-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_consejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Password123', max_length=128),
            preserve_default=False,
        ),
    ]
