# Generated by Django 5.2.6 on 2025-10-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_consejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
