# Generated by Django 5.2.6 on 2025-10-04 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0003_remove_ong_usuarios'),
        ('user', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ONG.ong'),
        ),
    ]
