# Generated by Django 5.2.6 on 2025-09-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ONG', '0001_initial'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participa',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.proyecto'),
        ),
    ]
