# Generated by Django 5.2.6 on 2025-10-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ONG', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='usuarios',
        ),
    ]
