# Generated by Django 5.2.6 on 2025-11-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('success', 'Éxito'), ('danger', 'Urgente')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.URLField(blank=True, help_text='URL de destino opcional', null=True),
        ),
    ]
